// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig():Promise<string>;

export function GetLang():Promise<string>;

export function InitConfig():Promise<void>;

export function Load_logger(arg1:number):Promise<void>;
