// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['service']['App']['GetConfig']();
}

export function GetLang() {
  return window['go']['service']['App']['GetLang']();
}

export function InitConfig() {
  return window['go']['service']['App']['InitConfig']();
}

export function Load_logger(arg1) {
  return window['go']['service']['App']['Load_logger'](arg1);
}
